### ISSUE TITLE
Remove type attributes from generated script and link tags as they aren't needed in HTML5

### ISSUE THREAD

**Issue by benedfit** [envygeeks/jekyll-assets#37]
Would be nice if this could be configured, or was off by default.

Gotta save those bytes where we can :)

**Comment by intemperie** [comment]
Any ideas why these are present again now? I'd like to get rid of them if possible.

**Comment by envygeeks** [comment]
They are there because I added them in 2.0.  It's not possible to remove them and I do not plan on adjusting the way that we do links anytime soon (if at all) because regardless of whether HTML5 supports them or not, I do not feel the need to mess with browsers that might be quirky for the sake of shaving a few negligible bytes.

**Comment by intemperie** [comment]
It's not like HTML5 supports them or not, but the fact that those are the defaults in HTML5 and are the ones applied if they're absent, so they're redundant/not needed. 

If you people are going to use any other doctype (which I doubt in almost 2017) they can just specify the attribute and that's it. It'd be really nice to be able to give people at least the option to make their code more optimal.

**Comment by bomberstudios** [comment]
Would you accept a pull request for this?

**Comment by envygeeks** [comment]
@bomberstudios @intemperie I would, as long as it's configurable (even if it defaults to being off and not showing up.)

**Comment by bomberstudios** [comment]
Awesome, will try to get something working next week 👍
