### ISSUE TITLE
Remove certain attributes from generated HTML

### ISSUE THREAD

**Issue by migueldemoura** [envygeeks/jekyll-assets#440]
- [X] I tried updating to the latest version.
  - [ ] I can't, there is an issue.
- [ ] I Am on Windows
- [ ] I Am on Bash on Windows
- [X] I Am on Linux
- [ ] I Am on OS X

## Description

When using the `asset` tag on css, for example, some attributes like `type`, `integrity` and `crossorigin` attributes are always set, and can't be removed with `!attribute_name`. Would it be possible for this to be implemented?

## Steps

- Step 1

`{% asset main.css !type !integrity !crossorigin %}
`
## Output

```html
<link integrity="sha256-example=" rel="stylesheet" type="text/css" href="/assets/main-example.css">
```

## Expected
```html
<link rel="stylesheet" href="/assets/main-example.css">
```

`Crossorigin` can be removed this way, but not the others.

PS: Sorry for the constant influx of issues from me :smile:

**Comment by envygeeks** [comment]
Why would you want the SRI removed?

**Comment by migueldemoura** [comment]
Bad example, though its usefulness in my specific case is reduced, as my blog, [migueldemoura.com](migueldemoura.com), has all resources served from the same domain.

The `type` attribute, however, isn't necessary with HTML5 in these default cases (js and css stylesheet).

**Comment by envygeeks** [comment]
Well, serving it from your own domain doesn't mean you don't need it, especially if they get clever and decide to drop a CoinHive attack into one of your already existing surfaces.  I doubt they would go back and adjust your SRI, but them directly adjusting a JS file to create a CoinHive attack hasn't happened yet, they simply just shim it into the HTML in the most direct way (note: We also make the SRI available in other ways so that your server can even create another surface for them to have to adjust before anything will work, but only if you utilize it.)

That said, I agree the type attribute isn't necessary, but that doesn't mean it should be removed.

I don't agree with the premise of why you want what you want, but I do feel that we should give you the option to exclude attributes if you wish, I've already been working on it tonight and will probably release it within a few hours.

---

*Remember, I accept tips, that's how I pay my bills and keep this software moving fast.*

**Comment by migueldemoura** [comment]
Absolutely, I agree with you on all points. I said "usefulness [...] is **reduced**", as it still provides the benefits you mentioned.
