### ISSUE TITLE
2.x to 3.x upgrade issues / guide

### ISSUE THREAD

**Issue by nickjj** [envygeeks/jekyll-assets#446]
Hi,

First up, congrats on the release 3.x.

I went to upgrade my project from 2.3 to 3.0 yesterday and ran into a couple of issues I couldn't get past so I reverted back to 2.3. Perhaps some of these issues could be turned into a migration guide at some point?

All of this was ran against 3.0 using sprockets 4.0.beta.

Here's what I noticed so far:

---

`{% image foo.jpg %}` tag no longer exists, it had to be changed to `{% asset foo.jpg %}`

---

This snippet used to work in 2.3 (using `image` instead of `asset`) but failed in 3.0. I know, I suck for not including the error (I've since reverted back to 2.3 and didn't realize I wanted to post this until now), but hopefully you can pick out what's wrong:

```
{% if page.card %}
  {% capture card %}{{ page.card }}{% endcapture %}
  {% asset {{card}} class:'post-card' %}
{% endif %}
```

---

This also failed in 3.0 because `asset_path` is gone. I couldn't figure out a solution to report back the file path of the image relative to the `images` directory. I tried using `{{ assets[card_image].filename }}` but it didn't work. I would like to get `blog/card/foo.jpg` back with the image residing in `_assets/images/blog/card/foo.jpg`. That is how it worked in 2.3.

```
{% assign card_image = page.card %}
{% asset_path {{card_image}} %}
```

---

Previously I had no extra configuration and these just worked because I have `main.scss` and `main.js` sitting in their expected directories. I tried `{% asset stylesheets/main.scss %}` but it would not work in 3.0 and these shortcut tags seem to be gone.

```
{% stylesheet main %}
{% javascript main %}
```

---

Previously I had these set up in my config and it's been so long that I forgot why I had them but the new README file for 3.0 doesn't have an inner `assets` key exists. Thoughts?

```
assets:
  assets:
    - '*.woff2'
    - '*.woff'
    - '*.tff'
    - '*.png'
    - '*.svg'
    - '*.gif'
    - '*.jpg'
```

**Comment by envygeeks** [comment]
Hi, thanks for the ticket.

> This snippet used to work in 2.3 (using image instead of asset) but failed in 3.0. I know, I suck for not including the error (I've since reverted back to 2.3 and didn't realize I wanted to post this until now), but hopefully you can pick out what's wrong:

That snippet would have never worked, and if it did that was a bug in my software, as we always required quotes around spaces when doing our parsing.  The new tag parser does use a relatively new algorithm introduced in Ruby 2.4 and backported by me to older rubies, but the effect should have been the same as the only thing it introduced was non breaking `"\""`.  It should be

```
{% if page.card %}
  {% capture card %}{{ page.card }}{% endcapture %}
  {% asset "{{ card }}" class=post-card %}
{% endif %}
```

but really it should be:

```
{% if page.card %}
  {% asset "{{ page.card }}" class=post-card %}
{% endif %}
```

This example notes this: 
- https://github.com/envygeeks/jekyll-assets#liquid
- https://github.com/envygeeks/jekyll-assets#arguments

---

> This also failed in 3.0 because asset_path is gone. I couldn't figure out a solution to report back the file path of the image relative to the images directory. I tried using {{ assets[card_image].filename }} but it didn't work. I would like to get blog/card/foo.jpg back with the image residing in _assets/images/blog/card/foo.jpg. That is how it worked in 2.3.

https://github.com/envygeeks/jekyll-assets#builtins

`{% asset_path %}` always returned an absolute path though, if it didn't that was a bug that was been resolved, but in theory it should have never of returned an unprefixed absolute URI.  If `site.assets[card].filename` didn't work, I think that's a bug in Liquid, we don't handle anything more than making the assets available, as long as they aren't a partial (AKA starts with `_` or the path they're in (read: directory) starts with a `_`)  The only way it would be a bug of mine is if somehow we aren't adding assets properly.

---

> Previously I had no extra configuration and these just worked because I have main.scss and main.js sitting in their expected directories. I tried {% asset stylesheets/main.scss %} but it would not work in 3.0 and these shortcut tags seem to be gone.

"stylesheets/" isn't on our list of sources, I don't remember if it was in 2.3... There are no plans to readd any tags. the only tag we have now is `{% asset %}`, it is the one tag to rule them all: https://envygeeks.io/2017/11/21/jekyll-assets-3-released#one-tag-to-rule-them-all, we also no longer support extensionless assets, if you want "main" you need to either do "main.css" to get the compiled asset or "main.scss" to get the raw asset.  This is because Sprockets no longer supports it, and tbqf I agree with them.  The reason this worked before was because each of those tags added the respective content type on your behalf, now we expect you to add it yourself with an extension, to avoid any confusion in a single tag system.  I think that's a much cleaner interface, and it's allowed me to focus on features, rather than caring about content types, wrappers, and other stuff.

As for "stylesheets/main.css" being allowed as a path, I don't know that that will work, but afaiw the way `find_asset!` works, is you need to either use the absolute path, or the path from the directory in the paths, so it needs only be "main.css" if "stylesheets" is in your sources.

---

> Previously I had these set up in my config and it's been so long that I forgot why I had them but the new README file for 3.0 doesn't have an inner assets key exists. Thoughts?

Use `precompile`, `assets:` is no longer supported, it was an unintuitive configuration option, and `precompile` is listed in the configuration example.  Though not necessarily noted inside of the documentation as I thought it was an obvious configuration.  I'll add it to my todo to update it.

**Comment by nickjj** [comment]
> That snippet would have never worked

I've been using it for many months on a very large site and it worked, but your adjusted value also works (at least in 2.3), but it fails in 3.0.

```
  {% if page.card %}
    {% asset "{{ page.card }}" class:'post-card' %}
  {% endif %}
```

It fails in 3.0 with `jekyll 3.6.2 | Error:  no implicit conversion of Symbol into Integer`

---

> site.assets[card].filename

Would you expect this to also work in 2.3 because that returns an empty string in 2.3.

I'm not sure what it outputs in 3.0 yet because the last bit of this reply is preventing me from starting the server.

---

> "stylesheets/" isn't on our list of sources, I don't remember if it was in 2.3

It wasn't by default, but I added it to my config with:

```yml
assets:
  sources:
    - _assets/stylesheets
    - _assets/javascripts
```

I'm not sure if `main.scss` and `main.js` alone will work because now when I run it with 3.0, it throws this error:

`jekyll 3.6.2 | Error:  couldn't find file 'bootstrap' with type 'application/javascript'`

In my `Gemfile` I have `gem 'bootstrap-sass', '~> 3.3'` set.

Then in my `main.scss` file I have:

```
@import 'bootstrap-sprockets';
@import 'bootstrap/variables';
```

All of this worked in 2.3 as is.

I also have:

```
@import 'font-awesome-sprockets';
@import 'font-awesome';
```

And in my `Gemfile` it has `gem 'font-awesome-sass', '~> 4.7'` and in this case, Jekyll searches through the fontawesome directory for paths but it does NOT search through the bootstrap paths.

---

If I remove the main tags (just to try and get the server to start) then I get greeted with:

`Liquid Exception: no implicit conversion of Symbol into Integer in /home/nick/Dev/Sites/nickjanetakis/_posts/2015-05-23-build-a-saas-app-with-flask-part-2.md`

I don't know what line it's associated to but this blog post has a bunch of images.

Those images are defined as so:

`{% asset blog/build-a-saas-app-with-flask-v1-admin-dashboard.jpg %}`

Previously they all worked in 2.3 using the `image` tag with those paths.

**Comment by envygeeks** [comment]
Don't compare 2.x to 3.x that deeply.  I do not take steps backwards when I spec out progression, so every problem is taken on a case-by-case basis on whether I intended it to never be like that, and won't ever let it be like that again, or whether it was unintended but acceptable. :smile: 

---

> Would you expect this to also work in 2.3 because that returns an empty string in 2.3.

I would, but it won't be fixed because 2.3 is EOL unless there is a critical security bug. In theory, I expect it to work, unless there is some quirky stuff going on with Liquid.  Or a bug in Liquid.  The most we do is create a drop, register a method with a `forwardable-extended` and then move along, past that point the interface is really decided by Liquid, and we don't do heavy integration testing so if the interface didn't work through Liquid we wouldn't necessarily notice, but we treat our drops the way their documentation states we should.

---

> It fails in 3.0 with jekyll 3.6.2 | Error: no implicit conversion of Symbol into Integer

I don't know what that means, it's pretty meaningless to me without 1.) Context and 2.) A trace.  Never provide an error without a trace because I can't magically deduce the error path, or even the context because that error doesn't happen on our fairly large sites that went 3.x weeks before it's final release.

You can run Jekyll with `--trace` if you wish to provide me with the trace.  If `jekyll-assets` isn't directly mentioned inside of the trace, it's probably not caused by me or my software, and it's just a coincidence, if it is, file a unique bug.

---

> jekyll 3.6.2 | Error: couldn't find file 'bootstrap' with type 'application/javascript'

We don't support `bootstrap-sass` anymore, I've updated the documentation.  Move to the official `bootstrap` gem that Bootstrap recommends if you wish for us to add it to your load path automatically, otherwise you need to create a plugin and register it yourself.

**Comment by nickjj** [comment]
Here's the trace. I didn't even know the `--trace` flag existed.

It looks related to your plugin.

```ruby
Liquid Exception: no implicit conversion of Symbol into Integer in /_layouts/post.html
bundler: failed to load command: jekyll (/home/nick/.gem/ruby/2.4.2/bin/jekyll)
TypeError: no implicit conversion of Symbol into Integer
  /home/nick/.gem/ruby/2.4.2/gems/jekyll-assets-3.0.1/lib/jekyll/assets/utils.rb:195:in `[]'
  /home/nick/.gem/ruby/2.4.2/gems/jekyll-assets-3.0.1/lib/jekyll/assets/utils.rb:195:in `prefix_url'
  /home/nick/.gem/ruby/2.4.2/gems/jekyll-assets-3.0.1/lib/jekyll/assets/plugins/html/defaults/img.rb:23:in `set_src'
  /home/nick/.gem/ruby/2.4.2/gems/jekyll-assets-3.0.1/lib/jekyll/assets/default.rb:87:in `block in run'
  /home/nick/.gem/ruby/2.4.2/gems/jekyll-assets-3.0.1/lib/jekyll/assets/default.rb:86:in `each'
  /home/nick/.gem/ruby/2.4.2/gems/jekyll-assets-3.0.1/lib/jekyll/assets/default.rb:86:in `run'
  /home/nick/.gem/ruby/2.4.2/gems/jekyll-assets-3.0.1/lib/jekyll/assets/default.rb:52:in `block in set'
  /home/nick/.gem/ruby/2.4.2/gems/jekyll-assets-3.0.1/lib/jekyll/assets/default.rb:47:in `each'
  /home/nick/.gem/ruby/2.4.2/gems/jekyll-assets-3.0.1/lib/jekyll/assets/default.rb:47:in `set'
  /home/nick/.gem/ruby/2.4.2/gems/jekyll-assets-3.0.1/lib/jekyll/assets/tag.rb:160:in `internal'
  /home/nick/.gem/ruby/2.4.2/gems/jekyll-assets-3.0.1/lib/jekyll/assets/tag.rb:57:in `render_raw'
  /home/nick/.gem/ruby/2.4.2/gems/jekyll-assets-3.0.1/lib/jekyll/assets/tag.rb:72:in `render'
  /home/nick/.gem/ruby/2.4.2/gems/liquid-4.0.0/lib/liquid/block_body.rb:109:in `render_node'
  /home/nick/.gem/ruby/2.4.2/gems/liquid-4.0.0/lib/liquid/block_body.rb:88:in `block in render'
  /home/nick/.gem/ruby/2.4.2/gems/liquid-4.0.0/lib/liquid/block_body.rb:75:in `each'
  /home/nick/.gem/ruby/2.4.2/gems/liquid-4.0.0/lib/liquid/block_body.rb:75:in `render'
  /home/nick/.gem/ruby/2.4.2/gems/liquid-4.0.0/lib/liquid/tags/if.rb:44:in `block (2 levels) in render'
  /home/nick/.gem/ruby/2.4.2/gems/liquid-4.0.0/lib/liquid/tags/if.rb:42:in `each'
  /home/nick/.gem/ruby/2.4.2/gems/liquid-4.0.0/lib/liquid/tags/if.rb:42:in `block in render'
  /home/nick/.gem/ruby/2.4.2/gems/liquid-4.0.0/lib/liquid/context.rb:123:in `stack'
  /home/nick/.gem/ruby/2.4.2/gems/liquid-4.0.0/lib/liquid/tags/if.rb:41:in `render'
  /home/nick/.gem/ruby/2.4.2/gems/liquid-4.0.0/lib/liquid/block_body.rb:109:in `render_node'
  /home/nick/.gem/ruby/2.4.2/gems/liquid-4.0.0/lib/liquid/block_body.rb:88:in `block in render'
  /home/nick/.gem/ruby/2.4.2/gems/liquid-4.0.0/lib/liquid/block_body.rb:75:in `each'
  /home/nick/.gem/ruby/2.4.2/gems/liquid-4.0.0/lib/liquid/block_body.rb:75:in `render'
  /home/nick/.gem/ruby/2.4.2/gems/liquid-4.0.0/lib/liquid/template.rb:208:in `block in render'
  /home/nick/.gem/ruby/2.4.2/gems/liquid-4.0.0/lib/liquid/template.rb:242:in `with_profiling'
  /home/nick/.gem/ruby/2.4.2/gems/liquid-4.0.0/lib/liquid/template.rb:207:in `render'
  /home/nick/.gem/ruby/2.4.2/gems/liquid-4.0.0/lib/liquid/template.rb:220:in `render!'
  /home/nick/.gem/ruby/2.4.2/gems/jekyll-3.6.2/lib/jekyll/liquid_renderer/file.rb:30:in `block (2 levels) in render!'
  /home/nick/.gem/ruby/2.4.2/gems/jekyll-3.6.2/lib/jekyll/liquid_renderer/file.rb:42:in `measure_bytes'
  /home/nick/.gem/ruby/2.4.2/gems/jekyll-3.6.2/lib/jekyll/liquid_renderer/file.rb:29:in `block in render!'
  /home/nick/.gem/ruby/2.4.2/gems/jekyll-3.6.2/lib/jekyll/liquid_renderer/file.rb:49:in `measure_time'
  /home/nick/.gem/ruby/2.4.2/gems/jekyll-3.6.2/lib/jekyll/liquid_renderer/file.rb:28:in `render!'
  /home/nick/.gem/ruby/2.4.2/gems/jekyll-3.6.2/lib/jekyll/renderer.rb:123:in `render_liquid'
  /home/nick/.gem/ruby/2.4.2/gems/jekyll-3.6.2/lib/jekyll/renderer.rb:188:in `render_layout'
  /home/nick/.gem/ruby/2.4.2/gems/jekyll-3.6.2/lib/jekyll/renderer.rb:155:in `place_in_layouts'
  /home/nick/.gem/ruby/2.4.2/gems/jekyll-3.6.2/lib/jekyll/renderer.rb:85:in `render_document'
  /home/nick/.gem/ruby/2.4.2/gems/jekyll-3.6.2/lib/jekyll/renderer.rb:62:in `run'
  /home/nick/.gem/ruby/2.4.2/gems/jekyll-3.6.2/lib/jekyll/site.rb:455:in `block (2 levels) in render_docs'
  /home/nick/.gem/ruby/2.4.2/gems/jekyll-3.6.2/lib/jekyll/site.rb:453:in `each'
  /home/nick/.gem/ruby/2.4.2/gems/jekyll-3.6.2/lib/jekyll/site.rb:453:in `block in render_docs'
  /home/nick/.gem/ruby/2.4.2/gems/jekyll-3.6.2/lib/jekyll/site.rb:452:in `each_value'
  /home/nick/.gem/ruby/2.4.2/gems/jekyll-3.6.2/lib/jekyll/site.rb:452:in `render_docs'
  /home/nick/.gem/ruby/2.4.2/gems/jekyll-3.6.2/lib/jekyll/site.rb:192:in `render'
  /home/nick/.gem/ruby/2.4.2/gems/jekyll-3.6.2/lib/jekyll/site.rb:73:in `process'
  /home/nick/.gem/ruby/2.4.2/gems/jekyll-3.6.2/lib/jekyll/command.rb:28:in `process_site'
  /home/nick/.gem/ruby/2.4.2/gems/jekyll-3.6.2/lib/jekyll/commands/build.rb:65:in `build'
  /home/nick/.gem/ruby/2.4.2/gems/jekyll-3.6.2/lib/jekyll/commands/build.rb:36:in `process'
  /home/nick/.gem/ruby/2.4.2/gems/jekyll-livereload-0.2.2/lib/jekyll-livereload/build.rb:30:in `process'
  /home/nick/.gem/ruby/2.4.2/gems/jekyll-3.6.2/lib/jekyll/commands/serve.rb:42:in `block (3 levels) in init_with_program'
  /home/nick/.gem/ruby/2.4.2/gems/jekyll-3.6.2/lib/jekyll/commands/serve.rb:42:in `each'
  /home/nick/.gem/ruby/2.4.2/gems/jekyll-3.6.2/lib/jekyll/commands/serve.rb:42:in `block (2 levels) in init_with_program'
  /home/nick/.gem/ruby/2.4.2/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
  /home/nick/.gem/ruby/2.4.2/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
  /home/nick/.gem/ruby/2.4.2/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
  /home/nick/.gem/ruby/2.4.2/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
  /home/nick/.gem/ruby/2.4.2/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
  /home/nick/.gem/ruby/2.4.2/gems/jekyll-3.6.2/exe/jekyll:15:in `<top (required)>'
  /home/nick/.gem/ruby/2.4.2/bin/jekyll:23:in `load'
  /home/nick/.gem/ruby/2.4.2/bin/jekyll:23:in `<top (required)>'
```

**Comment by envygeeks** [comment]
> I don't mind staying with 2.3 forever (since it works for me), but I wanted to try 3.0 because of the potential speed boosts.

Just don't plan on me not instantly closing bugs for it.  I encourage you to try 3.0 properly, there are a lot of changes, this isn't just a surface upgrade, this is a complete upgrade, this is a complete rewrite, this is  completely new system surfaced around performance and doing it right, rather than hacking it together overnight and continuing to hack it together for a year after that.

--

> It looks related to your plugin.

Your error is a user error caused by a lack of upgrading your configuration before trying to do anything, upgrade your configuration.  As for bootstrap, I'll consider it, but as requested you keep using the same ticket instead of filing unique issues.  File a unique issue if you have a request or a a proper error.

---

> Sorry for the unprovoked advice, but you might want to consider adding support back for bootstrap-sass

Then I would be supporting something I don't want to support, and am not being paid to support or debug, I have to write integration testing for it (we do, do this as an integration test.)  I know it seems like just as easy as adding a require but it's not.

**Comment by nickjj** [comment]
> Your error is a user error caused by a lack of upgrading your configuration before trying to do anything

I removed all of my configuration except for the custom `sources` path. It produces the same error.

When I updated to 3.0 my config was changed to:

```yml
assets:
  sources:
    - _assets/stylesheets
    - _assets/javascripts
```

> I encourage you to try 3.0 properly.

I've been trying for the last 3 hours across 2 days.

But, I think I'm just going to stay with 2.3 because no bootstrap 3 support is a deal breaker for me unfortunately and I can't fix the other issues addressed in this issue.

I know you don't get paid for support and debugging (and I appreciate you trying) but when you remove something as popular as bootstrap 3 and then EOL 2.3 (which is ok since it works well) then you're aliening a massive chunk of your audience. That's just going to hurt you in the end because if people aren't using your plugin then you have less chances of getting donations.

**Comment by envygeeks** [comment]
> I removed all of my configuration except for the custom sources path. It produces the same error.

We merge configurations, and that merge is heavily internally used in our tests so I assume if it were bugged we would spot the bug pretty quickly, but it could still be a bug... but that error leads me to believe there is something deeper going on, or that's not your full configuration because that line leads directly to this configuration:

https://github.com/envygeeks/jekyll-assets/blob/02b49abe2c0d53e59e21c4d113eb6fecb3b4bb60/lib/jekyll/assets/config.rb#L37-L41

If it were a string, it would cause that error.

https://github.com/envygeeks/jekyll-assets/blob/02b49abe2c0d53e59e21c4d113eb6fecb3b4bb60/lib/jekyll/assets/utils.rb#L195

> I know you don't get paid for support and debugging (and I appreciate you trying) but when you remove something as popular as bootstrap 3 and then EOL 2.3 (which is ok since it works well) then you're aliening a massive chunk of your audience. That's just going to hurt you in the end because if people aren't using your plugin then you have less chances of getting donations.

Nobody was donating before either, so we are at the OpenSSL point now. Where I won't be a single person managing a dozen different versions, of  dozen different projects, which will eventually lead to the demise of an entire project because of one massive problem.  You say doing what I did alienates people,  I say if they had donated even just a few dollars I wouldn't have to make the decision between continuing to support 2.3 or dropping support for it so I can focus on 3.0 and move forward.  You say you won't donate because I won't add "bootstrap-sass", I say if somebody had donated I wouldn't mind supporting it.  

I'm not worried about being hurt, because thanks to Github's new stuff I've discovered that I'm already being hurt, my projects are used by some of the largest and most popular projects and I see nothing coming in to support that effort.  A few people have donated, or literally paid me to do features, but for the most part, nobody wants to remember that it takes a massive amount of effort do what I did, and it will take a massive amount of effort to support 3.0 when the bugs start rolling in, including dealing with vendors who use my plugin, or my Docker images, or outright rely on them.

**Comment by nickjj** [comment]
Ah you know what. I am loading 2 configs. A default config and a development config (which overrides a few things). One of the development config options was setting `cdn: ''` inside of the `assets` key.

Even so, without bootstrap 3 I can't move forward for the time being. Is the custom plugin solution something you can just drop into the README where users can copy / paste it into `_plugins` and bootstrap-sass would continue to work?

**Comment by envygeeks** [comment]
That's the same as supporting it really, and a way to avoid the aforementioned problem of earlier.

**Comment by nickjj** [comment]
What's the same as supporting it? I'm not following you.

**Comment by envygeeks** [comment]
It's been readded.

**Comment by nickjj** [comment]
It still fails with `jekyll 3.6.2 | Error:  couldn't find file 'bootstrap' with type 'application/javascript'`.

This is with `{% asset main.js %}` and having bootstrap installed with bootstrap-sass.
