### ISSUE TITLE
Favicon anomaly

### ISSUE THREAD

**Issue by gasparesganga** [envygeeks/jekyll-assets#448]
- [x] I tried updating to the latest version.
  - [x] I can't, there is an issue.
- [ ] I Am on Windows
- [ ] I Am on Bash on Windows
- [x] I Am on Linux
- [ ] I Am on OS X

## Preamble
First of all, version 3 seems like a big improvement, thank you!
I'm trying to migrate all my projects and I'm experiencing a couple of anomalies. I'll post each of them in a separate issue.

## Description
I can't get the favicon to properly work.
- If I use the `{% asset %}` tag it gets generated  but nothing is included in the html output.
- If I use the liquid drop the html is correct, but no file gets generated in the output folder.

## Case 1 - Asset Tag
`{% asset img/favicon.ico %}`

File `assets/img/favicon-ad10b8480193d0c732ff8aa5d81cd941a475635d6b72c5cadcffb2543528d3b1.ico` is created but no `<link>` tag is written in the HTML.

## Case 2 - Liquid Drop
`<link rel="icon" href="{{ assets['img/favicon.ico'].digest_path }}">`

The resulting HTML is the expected one:
`<link rel="icon" href="/assets/img/favicon-ad10b8480193d0c732ff8aa5d81cd941a475635d6b72c5cadcffb2543528d3b1.ico">`

but not file is created in the output folder.

**Comment by envygeeks** [comment]
Case #2 is expected and intended behavior.  They are there as informational variables. As for case #1, does it do an `img` or any other tag? I know what the problem is for there being a lack of anything, and it's that we don't handle `ico` in our HTML builders, but if it writes an `img` then we are doing it wrong.

**Comment by gasparesganga** [comment]
I didn't know the liquid drops were there just as *informal variables*, thanks for the clarification.
No, nothing is created inside the output HTML.

**Comment by envygeeks** [comment]
Back in the day they were created so that people could explicitly get at a list of known assets for using them in things like `{% if assets[background.image] %}`, and then evolved as people wanted to get more information about their assets (such as image size, we provide image size, file name, and other stuff.) We could easily make them writable, considering `digest_path` is gonna be just as expensive no matter what, but the other pieces are pretty cheap.  You can file a separate ticket for that bit if you wish.

**Comment by gasparesganga** [comment]
By *make them writable* you mean the same exact use that I had in mind, ie:
`<a href="{{ assets['img/my_image.jpg'].digest_path }}">link text</a>` will process and create the asset, so in my HTML I will find the correct digest path **AND** the asset will be placed in the output folder, without any further reference to it?

PS: GitHub won't let me open another Issue for the moment, but I've got another one too. I'm testing extensively v3.
