### ISSUE TITLE
Only the first array element is processed inside a liquid for loop

### ISSUE THREAD

**Issue by gasparesganga** [envygeeks/jekyll-assets#449]
- [x] I tried updating to the latest version.
  - [x] I can't, there is an issue.
- [ ] I Am on Windows
- [ ] I Am on Bash on Windows
- [x] I Am on Linux
- [ ] I Am on OS X

## Description
When I try to loop through an array of assets, only the first one is always passed to the `{% asset %}` tag, even if the loop is working correctly.

## Steps
In *page.md* front matter:
```yaml
---
assets:
  js:
    - js/jquery.min.js
    - customfolder/_assets/file1.js
    - customfolder/_assets/file2.js
---
```

In *_layout.html*:
```html
{% for filename in page.assets.js %}
    {% asset '{{ filename }}' %}
    <!-- {{ filename }} -->
{% endfor %}
```

## Output
```html
<script type="text/javascript" src="/assets/js/jquery.min-9347a28e490a684188bc8e7748f6f086a53a87088854ac4de47095f42a085b5b.js" integrity="sha256-k0eijkkKaEGIvI53SPbwhqU6hwiIVKxN5HCV9CoIW1s=" crossorigin="anonymous"></script>
<!-- js/jquery.min.js -->

<script type="text/javascript" src="/assets/js/jquery.min-9347a28e490a684188bc8e7748f6f086a53a87088854ac4de47095f42a085b5b.js" integrity="sha256-k0eijkkKaEGIvI53SPbwhqU6hwiIVKxN5HCV9CoIW1s=" crossorigin="anonymous"></script>
<!-- customfolder/_assets/file1.js -->

<script type="text/javascript" src="/assets/js/jquery.min-9347a28e490a684188bc8e7748f6f086a53a87088854ac4de47095f42a085b5b.js" integrity="sha256-k0eijkkKaEGIvI53SPbwhqU6hwiIVKxN5HCV9CoIW1s=" crossorigin="anonymous"></script>
<!-- customfolder/_assets/file2.js -->
```

That's very weird since the `filename` variable contains the right element at each iteration.

**Comment by envygeeks** [comment]
Please provide a repository with a minimum example.  That demonstrates the problem on a clean repo.

**Comment by gasparesganga** [comment]
Here you go: https://github.com/gasparesganga/test-jekyll-assets

It took me a little more time because I wanted to check if my particular folder structure was involved with it or that's just something related to the for loop. It definitely happens in any for loop.

The `_site/index.html ` output file will clearly show the bug both with CSS and JS files: only `_assets/css/file1.css` and `_assets/js/file1.js` are processed, despite being looped correctly.

**Comment by envygeeks** [comment]
I'm not worried about what worked flawlessly in 2.x, if I was I wouldn't have rewrote the entire thing for the improvements it has, I would have stalled like Jekyll Core itself and made no real progress in the last few years, especially in the speed and efficiency department.

I don't know that this is a bug on my end either, we literally use Jekyll's Liquid processor to deal with processing Liquid, and the loop isn't even handled by us, and sometimes we find ways to work around Jekyll, sometimes I flat out refuse to fix a problem because to do so would be to work around somebody else code in a way I don't like.  Previously we used bits of it, but we also backtracked to work around a lot of the nonsense (if I remember right.) But we took our Liquid processing directly from how Jekyll does it itself inside of it's own include tags, upped the game by passing around the context from the tag, but we don't (within Jekyll assets, cache anything on that end.)  I'll have a look, but there are no promises I refuse to fix in favor of forcing Jekyll to actually do something about their source if it is their bug, otherwise I'll get it fixed ASAP if it is my bug.

**Comment by gasparesganga** [comment]
Yep the information about the old version and the fact that the same loop used to work was simply that, an information. As a developer I like to know as many details as possible, sometimes even the smallest detail can *trigger the idea* about what's going on.

I am testing v3 extensively, it's a sweet piece of software so I'm glad I can contribute at least by doing some tests. Thank you

**Comment by migueldemoura** [comment]
Can you test by having multiple asset tags one after the other, without the loop, in the same file? I get the same file that way as well.

**Comment by envygeeks** [comment]
Please file another issue, your issue is unrelated, regardless.  This is about looping.
