### ISSUE TITLE
js, css, stylesheet, etc tags are missing

### ISSUE THREAD

**Issue by asgarli** [envygeeks/jekyll-assets#466]
Is the above intentional? 

Is there a migration guide from v2 to v3?

**Comment by envygeeks** [comment]
The migration guide is the documentation, it was updated and cleaned up as development was happening.  You can also read https://envygeeks.io/2017/11/21/jekyll-assets-3-released, use `{% asset %}` as the documentation states, we no longer need all the other complexity other tags provide because Sprockets 4.x has provided what we used to do, and enforced what we used to have to work around, though I'm not against readding them, but since this is one of only two times this has come up, there is a lack of votes for such a thing.

Thanks!
