### ISSUE TITLE
Upgrade to 3.x broke liquid tags in css files

### ISSUE THREAD

**Issue by DanielSt** [envygeeks/jekyll-assets#470]
I am currently using Jekyll-assets 2.4.0. I am using liquid tags in my css files to get the asset_path, like this:

`src: url('{% asset_path folio/fontawesome-webfont.eot %}');`

Upgrading to the latest version breaks this, as liquid tags are not being evaluated in pure css files anymore. Instead I get the raw code line inserted into the final css.

How can I fix this to upgrade to the latest version, without rewriting all my css files? Thanks :-)

**Comment by envygeeks** [comment]
This is documented here: https://github.com/envygeeks/jekyll-assets#liquid-1

**Comment by envygeeks** [comment]
Actually, it's not that well documented, and it's got some bad examples, so I'm gonna leave this open so I remember to update that section. the short of it is.  If you want full liquid processing use `.liquid.scss`, if you want only pieces without breaking anything then use `asset_url` helper, instead of `{% asset_path %}` or `{% asset %}`, it's weird that you would opt to use that anyways considering our helpers for SASS have always use Sprockets context.  The only way for CSS is `.liquid.css`, if that doesn't work, then please do update this ticket, and I'll make sure it's added to the list of transformers for Liquid.
