### ISSUE TITLE
There is no migration guide

### ISSUE THREAD

**Issue by xRahul** [envygeeks/jekyll-assets#479]
- [x] I tried updating to the latest version.
  - [x] I can't, there is an issue.
- [x] I Am on OS X

## Description

Many tags like `asset_path` and `asset_source` stopped working after the update. It'd be helpful if there was a migration guide on the tags that are no longer supported, and how to replace them.

**Comment by envygeeks** [comment]
They didn't stop working, they were removed in their entirety, and our interfaces became more streamlined.  They are unnecessary in the current version because we now use `liquid-tag-parser` which provides a very robust interface to parsing tag arguments compared to the old home grown one we used before (note: `liquid-tag-parser` is actually grown out of this projects original tag parser.)  That said, my site has a post about what's changed, I'll consider writing a document about it on my site past what is already there but I don't know when I'll have the time to do it as my major focus is fixing bugs.

**Comment by xRahul** [comment]
Thank you. Can you add a link to the post until then? It'd be a helpful resource to get a general idea at least

**Comment by tylercampbell** [comment]
https://envygeeks.io/2017/11/21/jekyll-assets-3-released

**Comment by schneems** [comment]
That link no longer works @tylercampbell do you have a working copy?

**Comment by tylercampbell** [comment]
> That link no longer works @tylercampbell do you have a working copy?

My link was to a blog post by the jekyll-assets author. I believe he's since incorporated that blog post's content into the official readme, but feel free to view the blog post here: https://envygeeks.io/blog/2017/11/21/jekyll-assets-3-released

**Comment by ttencate** [comment]
The link is dead and not present in the WayBack Machine either :(
