### ISSUE TITLE
{{ assets[] }} throws undefined method `index'

### ISSUE THREAD

**Issue by cameronmcefee** [envygeeks/jekyll-assets#480]
- [x] I tried updating to the latest version.
- [x] I Am on OS X

## Description

When I try to reference an asset according to the documentation, I get 
I've tried with various types of assets. It only throws the error when the referenced asset exists. If the asset does not exist, nothing happens.

## Steps

- Checkout this repo and this commit: https://github.com/getsentry/sentry-docs/commit/031bc68313aa44c8fc2a9caf77b2edc581cc8323
- Add `{{ assets['screen.scss'].digest_path }}` somewhere. I put it in `src/_layouts/default.html`
- Run bin/server to start Jekyll

## Output

```sh
Configuration file: _config.yml
Configuration file: _config.dev.yml
            Source: src
       Destination: /Users/cameronmcefee/github/sentry-docs/_site
 Incremental build: enabled
      Generating... 
           Assets:  Compression is ignored w/ SourceMaps
  Liquid Exception: undefined method `index' for #<Pathutil:meta/default> in /_layouts/default.html
jekyll 3.6.2 | Error:  undefined method `index' for #<Pathutil:meta/default>
```

## Expected

The html should display the digest path to the file referenced

**Comment by envygeeks** [comment]
It should be noted that none of those methods will return any sort of HTML, they will only return regular text, in your case, simply just the digested path, in the meantime, since I do not have a release date set till late next week you can get the same data with `{% asset screen.css @path %}` as the documentation notes.  In the current system they are one in the same and will both force a compile in your case to get the digested path.

**Comment by cameronmcefee** [comment]
Ah nice, that works for me.
