### ISSUE TITLE
Is it possible to toggle the output of cache busting asset names?

### ISSUE THREAD

**Issue by kylekirkby** [envygeeks/jekyll-assets#490]
- [x ] I tried updating to the latest version.
- [x ] I Am on Linux

## Description

I've updated to the latest version of jekyll-assets and noticed that the cache busting hashed filenames are on by default. Is there a way to toggle this feature for images as now all images included have a long hashed filename. I understand this may help with JS/CSS but we would like it if people could download images with the original filename. Is this possible?

## Steps

Using jekyll-assets version 3.0.6 - look at the filenames of assets included via the {% asset 'awesome_image.png' @path %} tag.

## Output
src="/assets/Linaro-Sprinkle-863ad1a40f62804d3a6d2c6828e82e351e706048ab1f17961365bef5025f27c2.png"

## Expected

src="/assets/Linaro-Sprinkle.png"

Many Thanks,

Kyle

**Comment by envygeeks** [comment]
There is a way and you have to view the source to find it, it's undocumented, unsupported and there only for a client who funded it for themselves.  It will remain so until I can convince them to use the Metadata file I provide instead of that, and then it will be removed, so don't rely on undocumented features.

**Comment by kylekirkby** [comment]
Ok sure completely understand - all the best.
