### ISSUE TITLE
Incorrect src path on asset @pic <img> tag

### ISSUE THREAD

**Issue by migueldemoura** [envygeeks/jekyll-assets#501]
- [X] I tried updating to the latest version.
  - [ ] I can't, there is an issue.

- [ ] I Am on Windows
- [ ] I Am on Bash on Windows
- [X] I Am on Linux
- [ ] I Am on OS X

## Description

Path is missing a `/` for the `picture` > `img` element on `asset @pic`.

## Steps

```
{% asset 'image.png' @pic
        srcset:max-width=400
        srcset:max-width=200
%}
```

## Output

``` html
<picture>
<source srcset="/assets/400.png 400w" media="(max-width: 400px)">
<source srcset="/assets/200.png 200w" media="(max-width: 200px)">
<img src="path/image.png">
</picture>
```

## Expected

``` html
<picture>
<source srcset="/assets/400.png 400w" media="(max-width: 400px)">
<source srcset="/assets/200.png 200w" media="(max-width: 200px)">
<img src="/path/image.png">
</picture>
```

**Comment by envygeeks** [comment]
Can you please provide more information or a repository that can be shimmed to replicate this issue. While checking this issue it does seem that we do provide the proper path: https://github.com/envygeeks/jekyll-assets/blob/master/lib/jekyll/assets/plugins/html/pic.rb#L39

**Comment by migueldemoura** [comment]
Thanks!

**Comment by envygeeks** [comment]
This, is still a bug, depending on circumstances when proxies are ran we will return the wrong path on a second run, this is because we cache incorrectly.  We should be wrapping the entire logic, and catching a path, based on a digest of the arguments, this way we can determine if proxies have ran, and then get the path of the result without having to run everything again.

That said, this is about to be fixed *again*

**Comment by envygeeks** [comment]
Oh it look like this was about pics, not proxies.  I cannot read.
