### ISSUE TITLE
Drop type attribute from script tag

### ISSUE THREAD

**Issue by devraj** [envygeeks/jekyll-assets#510]
## Description

W3C validations service says that the `type` attribute in a `script` tag is not required, at present `Jekyll-Assets` generates `script` tags with the `type` attribute.

This request is to consider dropping the `type` attribute.

## Output

```
<script type="text/javascript" integrity="sha256-YkbF4PW30Z3IWwXPvZDJTwo8kRtdRORueptX3w3cLwg=" crossorigin="anonymous" src="/assets/ga.js"></script>
```

## Expected

```
<script integrity="sha256-YkbF4PW30Z3IWwXPvZDJTwo8kRtdRORueptX3w3cLwg=" crossorigin="anonymous" src="/assets/ga.js"></script>
```

**Comment by envygeeks** [comment]
You can do `{% asset whatever.jpg !type %}` to remove it.  As for removing it as a default, that would have to be a 3.1 thing, because it's been the default since the inception of Jekyll-Assets, because people use it on older browsers, I'm still hesitant to to even do it then considering it doesn't hurt anything, and the W3C validator (if it's nu) is just being hyperbolic like it's always been.

**Comment by migueldemoura** [comment]
Fairly sure you can safely remove it, @envygeeks, but the option to disable it with `!type` is sufficient for me at least.
