### ISSUE TITLE
Not able to use "precompile" and "raw_precompile" due to insufficient documentation

### ISSUE THREAD

**Issue by paulodeleo** [envygeeks/jekyll-assets#519]
Other than the comment on the README and the sample provided on the [blog post](https://envygeeks.io/2017/11/21/jekyll-assets-3-released), I couldn't find any example of usage of `raw_compile` and `raw_precompile`, and, unfortunally, I am unable to get how it work by [reading the source](https://github.com/envygeeks/jekyll-assets/blob/9b087f21373490d439c4ea6657a68850a220a367/lib/jekyll/assets/utils.rb#L62).

My need is to have all my minified (or not?) vendor javascript files (like jquery, jquery-ui, etc) inside a `_assets/js/vendor/` folder and, as fast as possible, compile them into a single `_site/assets/js/vendor.js` file to be loaded by `{{asset vendor.js}}`. 

Is that the intended usage for `raw_compile` and / or `raw_precompile`? If so, how can I achieve this? If not, could you provide any more detailed usage? What is the difference between the two, in practice? The YAML syntax regarding `src:` and `dst:` are particularly not explained to me.

**Comment by envygeeks** [comment]
On the src, and dst problem.  Please explain how they are confusing, I find it's wasteful to go on assumptive pursuits.  This is a 1 in 300K issue.  If it clarifies anything they mean "source" and "destination" (I have considered changing them to their full terms, and if you like that please file another ticket to spark a debate.)

Both the blog post, and the documentation state (in the comment, in the configuration example,) `raw_precompile` skips the asset pipeline in it's entirety. This is designed behavior, it exists solely for copying assets in whole to your asset folder for things like large sets of emoji's where they are *already optimized*, need to remain as is (name wise) and otherwise. They are literally copied.  If you're looking for microfast, that's not gonna happen if you go through the pipeline, any pipeline, which is the only way to concatenate into "vendor.js". And there is no way to skip things like compression, recompression, and otherwise once they enter the pipeline, on a perfile basis, it's either all or none, and I feel if you would like that, it need be taken up with Sprockets to see what they've to say about adding in a comment to handle it.

Raw files do not support `{{ asset }}` and if you use that tag with a raw asset, it will compile.

---

What you probably want to do is run it through the pipeline, and since it's a vendor'd asset, it should cache, without changing, and output microfast from the cache, as long as the vendor stuff doesn't change.

**Comment by paulodeleo** [comment]
Thanks for the super fast reply @envygeeks !

Regarding src and dst, as a rubyst, I prefer more natural, not abbreviated terms. But it is just a personal preference.

> What you probably want to do is run it through the pipeline, and since it's a vendor'd asset, it should cache, without changing, and output microfast from the cache, as long as the vendor stuff doesn't change.

That's what I was doing and getting over 20 seconds compile times on every file change, then I started playing with `raw_precompile`. It turns out that it was something wrong in my setup that was causing such long compile times. After some refactoring, it returned to sub 1 second compile times.

Well, regardless of not needing to use it for now, I tried again to use `raw_precompile` on a new project, just to see if I got your explanations right.

This is my project (output from `tree`):
```
.
├── _assets
│   └── vendor
│       ├── large_vendor_script_1.js
│       ├── large_vendor_script_2.js
│       └── large_vendor_script_3.js
├── _config.yml
├── Gemfile
├── Gemfile.lock
└── index.html
```
And this is my `_config.yml`:
```
plugins:
  - jekyll-assets
assets:
  raw_precompile:
    - src: vendor/*.js
      dst: vendor
```
I was hoping that after running `jekyll build` I would get files like this:

```
.
├── _assets
│   └── vendor
│       ├── large_vendor_script_1.js
│       ├── large_vendor_script_2.js
│       └── large_vendor_script_3.js
├── _config.yml
├── Gemfile
├── Gemfile.lock
├── index.html
└── _site
    ├── assets
    │   └── vendor
    │       ├── large_vendor_script_1.js
    │       ├── large_vendor_script_2.js
    │       └── large_vendor_script_3.js
    └── index.html
```
But my `_site/assets` folder is empty.

So I ask:

1. The `vendor` folder is correctly located inside `_assets`, right? Otherwise the standard jekyll build would copy the folder;
2. The `src:` and `dst:` paths should be relative to `_assets`, right? Is something like "./vendor" needed?
3. Why it didn't work, and what is the correct way to make it work?

**Comment by sylvainmetayer** [comment]
@paulodeleo  Did you solve this one ? I could be interested as I'm facing a similar issue.

**Comment by paulodeleo** [comment]
Unfortunally not, @sylvainmetayer. I ended up rebuilding the project structure to avoid local processing of large vendor assets, mostly by making extra requests to CDN's.

**Comment by sylvainmetayer** [comment]
Thanks for your answer, I'll let you know if I find something !
