### ISSUE TITLE
Feature missing from older versions

### ISSUE THREAD

**Issue by rezaalavi** [envygeeks/jekyll-assets#539]
We recently decided to upgrade from version 1.x to the latest version. In version one <% asset %> tag prints the content of the asset.

Unfortunately I cannot find any method to achieve the same functionality with the current version.

**Comment by envygeeks** [comment]
Please have a glance over the readme. https://github.com/envygeeks/jekyll-assets#jekyll-assets

**Comment by rezaalavi** [comment]
We spend a whole week moving all our projects to the new version and you assumed we did not read your readme file ?

I can assure you that not only I read the readme file. I check the code for the drop section.

**Comment by rezaalavi** [comment]
Could you at least point to the part in your readme file that we missed?

**Comment by envygeeks** [comment]
https://github.com/envygeeks/jekyll-assets#built-in We only support data uri for non text content.  If you use ERB you need to read Sprockets documentation, we do not directly support ERB, we just don't disable it.

**Comment by envygeeks** [comment]
I don't even know what you're talking about so you'll have to elaborate your use case further.  On the further question as to whether "this is a problem", it's a major version, things are going to change that's why it's a major version. If you would like a feature readded, or think a feature was wrongly moved then state your case, but trying to guilt me from progressing my software isn't gonna work, because that's not how major versions of software works.

**Comment by rezaalavi** [comment]
I can see that I am having trouble here.

You are probably having a bad day otherwise a simple question shouldn't have been handled like this.
All I wanted to know was to know how to do something that was possible in previous version.

Is there anyway we can access the contents of a our css and javascript or with version 3 we can only link to them?

Unfortunately it starts to seem like you assume your plugin users are a bunch of clueless people. Otherwise I cannot see why you have to be so rude in your responses, linking to a readme file or lecturing about how versioning works. 

I can assure you though after 25 years of programming I know how versions work. I have already read your code and your readme files and as I said before I and my team have spent a week of development time moving to the latest version so we know that things has changed.

I will probably have a post on this issue on our company blog post. Companies like us need to understand what the risks of using your code in production are. We are going to move our code to webpack and don't bother and waste our time and resources anymore.

**Comment by envygeeks** [comment]
I don't assume anything about my users, or about anybody.  I don't have time to pass judgment on people. Threatening to slander somebody should go over real easy.  Your company doesn't fund my work, has never offered to fund my work, and because I won't go out of my way for *free* to do what you want or to pander to you, you think slandering somebody is okay.  That's laughable.  I pointed to the documentation, and responded in kind to your threatening demeanor.

I pointed to the area of the documentation that shows you how to do what you wish (or close to it,) if you, or your team had actually read the documentation from top to bottom you would know by now that you could do `{% asset asset.css @inline %}` and got nearly what you wanted, and if that didn't work for you, you could have built a quick plugin: https://github.com/envygeeks/jekyll-assets#building-your-own-plugins to do anything you want to do, and as stated, we don't provide direct access to our objects, and if you expect that, it's not going to happen, that's a limitation in Jekyll.

Have fun with webpack.
