### ISSUE TITLE
Add support for Jekyll 4.0

### ISSUE THREAD

**Issue by ashmaroli** [envygeeks/jekyll-assets#553]
**This is not a bug-report**

---

### Background

Jekyll 4.0 is planning to improve build times by caching parsed Liquid Templates.
Proposed Ideas: jekyll/jekyll#7136 (considerably stable) and jekyll/jekyll#7169 (WIP)

While the fundamental result of both PRs are more or less the same for Jekyll Assets, this ticket is just about `jekyll/jekyll#7136`.

---
### Details

A known side-effect of `jekyll/jekyll#7136` is that since a Liquid tag is initialized just once per given markup token, (*i.e. `{% asset foo.js %}` in a template is going to create just a single instance of `Jekyll::Assets::Tag` irrespective of how many times the template is used.*), the tag is going to render the same output if the data hash provided to it is cached as well.

*Reference: https://github.com/aarongustafson/jekyll-webmention_io/issues/81#issuecomment-411419794*

A similar observation was seen with `{% seo %}` where every generated page had the same metadata. The "issue" there could however be resolved with a simple diff:

```diff
def drop
- @drop ||= Jekyll::SeoTag::Drop.new(@text, @context)
+ Jekyll::SeoTag::Drop.new(@text, @context)
end
```

But, I was unable to pinpoint where the data hash or drop passed to the "asset tag" is cached and would like your assistance with it.

**Comment by DirtyF** [comment]
⚠️ It's still  too early to ask plugin authors to test caching, when the new cache API is not well definded, let's hold on until a proper RC version is released. ⌛️

**Comment by ashmaroli** [comment]
Like I mentioned in the ticket body, this **is not** about the WIP Cache API but strictly in context of my PR `jekyll/jekyll#7136` ..

**Comment by DirtyF** [comment]
Same rule applies, wait for a beta or RC release before contact plugins authors about possible changes.

**Comment by envygeeks** [comment]
I'm confused as to what's going on, and since I can't ask for clarification on Jekyll, you'll have to clarify here.  We provide our caching, and have no plans to rely on Jekyll for caching (in that we won't ever rely on Jekyll for caching,) if this is about tag caching you'll need to elaborate a bit more.

As for why our drops, and tags, and filters are confusing, it's because they're all the same thing to Jekyll-Assets, we take KISS, and shared code to the max around here, if you can show me an RC once it's available, I'll happily see about working with Jekyll Tag caching (though that wont help us much since we already optimize around that internally.)

**Comment by ashmaroli** [comment]
@envygeeks Thank you for responding to this ticket. I'll get back to you once Jekyll ships a `v4.0.0.rc`

**Comment by nhoizey** [comment]
I know this is not a priority right now, but I just want to inform you that this currently breaks Jekyll master branch.

**Comment by ashmaroli** [comment]
@nhoizey Since Frank and I have already asked Jordon to wait till Jekyll ships a `beta` or `rc`, Can we move this discussion to your blog's repository..?
Thanks.

**Comment by envygeeks** [comment]
@ashmaroli Keeping me in the dark, and then expecting me to rush changes is not going to work out that well. I'm a single developer, to your team, so if you have information it's best to share it early, instead of expecting rushable changes that only push the blame onto me.

@nhoizey do you have any errors you can supply? Or debug logs.

**Comment by DirtyF** [comment]
@envygeeks does previous comments and https://github.com/ashmaroli/jekyll/blob/master/docs/_docs/upgrading/3-to-4.md#template-rendering help?

**Comment by nhoizey** [comment]
@envygeeks I don't have any error during build, I have an issue with the result of the build.

Like before in https://github.com/aarongustafson/jekyll-webmention_io/issues/81#issuecomment-411419794 I get the same content in the resulting HTML for all assets.

I don't know how @ashmaroli then fixed this issue for the jekyll-webmention_io plugin.

I can give you any log you want, if it helps.

**Comment by envygeeks** [comment]
It's fixed.

**Comment by ashmaroli** [comment]
@nhoizey To clarify, I did not fix a similar issue in `jekyll-webmention_io`.. You have misunderstood..
@envygeeks I did not intend to keep you in the dark. That's why this ticket was still open. I was just respecting Frank's request to wait till Jekyll ships a `4.0.0.pre`..

**Comment by envygeeks** [comment]
The changes have been picked into 3.0-current, and released as v3.0.12.  Good luck.

**Comment by ashmaroli** [comment]
Thanks for the quick response, Jordon :smiley:

**Comment by nhoizey** [comment]
Thanks a lot Jordon, I'll try a build ASAP!

**Comment by nhoizey** [comment]
I confirm that this works perfectly with both Jekyll 3.8.5 and `master` branch, thanks again @envygeeks !
