### ISSUE TITLE
SRI Digest Hash Algorithm sha256 Doesn't Meet Recommended Baseline of sha384 

### ISSUE THREAD

**Issue by mattt** [envygeeks/jekyll-assets#582]
- [x] I tried updating to the latest version
  - [ ] I can't, there is an issue
  - [ ] This is about an < latest
    - [ ] I understand older versions may be unsupported
- [ ] I Am on Windows
  - [ ] Ubuntu Bash on Windows
  - [ ] Fedora Bash on Windows
  - [ ] Other  Bash on Windows
- [ ] I Am on Linux
  - [ ] Ubuntu
  - [ ] Fedora
  - [ ] CentOS
  - [ ] Redhat
  - [ ] Debian
- [ ] I am on macOS 10.13
- [x] I am on macOS 10.14
- [ ] I'm on Docker
  - [ ] I understand Docker may be unsupported

## Description

When subresource integrity is enabled, Jekyll-Assets uses sha256 to calculate the digest. However, this algorithm doesn't meet the [baseline recommendations from the Subresource Integrity specification](https://w3c.github.io/webappsec-subresource-integrity/#hash-collision-attacks).

Jekyll-Assets should instead use sha384 by default, and optionally allow for this to be configured (as discussed in #535).  

## Steps

- Enable subresource integrity in a Jekyll project that uses Jekyll-Assets
- Use the `{% asset %}` tag to include a script or stylesheet.

## Output

```html
<link rel="stylesheet" type="text/css" href="screen.css" integrity="sha256-_______" crossorigin="anonymous">
```

## Expected

```html
<link rel="stylesheet" type="text/css" href="screen.css" integrity="sha384-_______" crossorigin="anonymous">
```

**Comment by TCFox** [comment]
Possibly related to #270 ?

Don't quote me on this, but as far as I know SHA256 is not currently considered _unsafe_ (as of 2019) and the convention to use SHA384 is largely due to [an old bug in Firefox that resulted in SHA256/SHA512 SRI hashes being incorrectly validated](https://bugzilla.mozilla.org/show_bug.cgi?id=1269241). SHA224/SHA384 was being validated correctly despite this bug, hence the convention to use it over SHA256.

I may have some of those details wrong, so apologies if that's not the exact story. It's based on some very fuzzy memories of how it all happened. Still would be great to see it changed to SHA384 and align it with W3C recommendations however I don't _think_ it's an issue based on security concerns.
