### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by xu-cheng** [envygeeks/jekyll-assets#627]
Hi, I would like to ask about the current state of this project. Is this project still maintained? 

I ask because the latest stable release (3.0.12) is over a year old and there is no update for the past several months. It would be nice if this project gets more maintenances especially for the support of Sprockets 4.0.0 (#620) and Jekyll 4.0 (#613).

Any feedback would be appreciated. Thanks.

**Comment by envygeeks** [comment]
A lot of people use this project but very few people deem it worth supporting so it's in an ironic state where I have to focus on other places, I am indeed very aware of the issues and constantly paying attention but most of those are waiting until I can give it free time because not many people are willing to help fund the part-time it would  take to do the overhaul for Sprockets 4, and Jekyll 4.0 full-on support.  It is not dead, I have not given up and still hold hope I'll get to it soon.

**Comment by uberfuzzy** [comment]
Is there any other project that is comparable that we can transition over to it and off of this semi-abandoned one, so we can start using Jekyll 4?

I fully understand that this is a volunteer project, but patchs([1]) and PRs have been sitting in stale PR hell for a while now to some of the major blockers to get over the hurdle of "even building" with the combo of jek4+assets4+spr4 without using someone's personal fork branch and a beta branch of a dependancy.

[1]: https://github.com/envygeeks/jekyll-assets/pull/620/files#diff-e1095c5b8621df290f3610849ab67948R46
